# Generated by Django 5.2.8 on 2026-03-08 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0003_subject_teachersubjectassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOutline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Course title, e.g. 'Numerical Methods - Math 4543'",
                        max_length=300,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Course code extracted from PDF",
                        max_length=50,
                    ),
                ),
                (
                    "course_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of course objective strings",
                    ),
                ),
                (
                    "raw_pdf",
                    models.FileField(
                        help_text="Original uploaded course outline PDF",
                        upload_to="curriculum/outlines/",
                    ),
                ),
                (
                    "parsing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "parsing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if parsing failed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_outlines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teaching_assignment",
                    models.OneToOneField(
                        help_text="The teaching assignment this outline belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_outline",
                        to="students.teachersubjectassignment",
                    ),
                ),
            ],
            options={
                "db_table": "course_outlines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseWeek",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("is_exam_week", models.BooleanField(default=False)),
                (
                    "exam_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Midterm Examinations'",
                        max_length=100,
                    ),
                ),
                (
                    "course_outline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="curriculum.courseoutline",
                    ),
                ),
            ],
            options={
                "db_table": "course_weeks",
                "ordering": ["course_outline", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within week or parent"
                    ),
                ),
                (
                    "course_outcomes",
                    models.JSONField(
                        blank=True, default=list, help_text='e.g. ["CO1", "CO2", "CO3"]'
                    ),
                ),
                (
                    "course_outline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="curriculum.courseoutline",
                    ),
                ),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent topic for hierarchical nesting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="curriculum.coursetopic",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        blank=True,
                        help_text="Week this topic is taught in",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="curriculum.courseweek",
                    ),
                ),
            ],
            options={
                "db_table": "course_topics",
                "ordering": ["course_outline", "order"],
            },
        ),
        migrations.CreateModel(
            name="TeacherNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("DIFFICULTY_THRESHOLD", "Difficulty Threshold Exceeded")
                        ],
                        default="DIFFICULTY_THRESHOLD",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("flag_count", models.PositiveIntegerField()),
                ("total_students", models.PositiveIntegerField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_outline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="curriculum.courseoutline",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="curriculum.coursetopic",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicDifficultyFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional detail on what is hard",
                    ),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_flags",
                        to="curriculum.coursetopic",
                    ),
                ),
            ],
            options={
                "db_table": "topic_difficulty_flags",
            },
        ),
        migrations.CreateModel(
            name="TopicMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "material_type",
                    models.CharField(
                        choices=[("FILE", "File"), ("LINK", "External Link")],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="curriculum/materials/"
                    ),
                ),
                (
                    "external_link",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="curriculum.coursetopic",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "topic_materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="curriculum.coursetopic",
                    ),
                ),
            ],
            options={
                "db_table": "topic_progress",
            },
        ),
        migrations.AddIndex(
            model_name="courseoutline",
            index=models.Index(fields=["created_by"], name="co_creator_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courseweek",
            unique_together={("course_outline", "week_number")},
        ),
        migrations.AddIndex(
            model_name="coursetopic",
            index=models.Index(
                fields=["course_outline", "week"], name="ct_outline_week_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursetopic",
            index=models.Index(fields=["parent_topic"], name="ct_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="teachernotification",
            index=models.Index(
                fields=["teacher", "is_read"], name="tn_teacher_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachernotification",
            index=models.Index(
                fields=["teacher", "created_at"], name="tn_teacher_time_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topicdifficultyflag",
            unique_together={("student", "topic")},
        ),
        migrations.AlterUniqueTogether(
            name="topicprogress",
            unique_together={("student", "topic")},
        ),
    ]
