# Generated by Django 5.2.8 on 2026-03-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_requests", "0008_contentrequestmodel_curriculum_topic"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmaterial",
            name="content_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked content request for AI-generated materials",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_materials",
                to="content_requests.contentrequestmodel",
            ),
        ),
        migrations.AlterField(
            model_name="topicmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("FILE", "File"),
                    ("LINK", "External Link"),
                    ("GENERATED", "AI-Generated Content"),
                ],
                max_length=10,
            ),
        ),
    ]
