# Generated by Django 5.2.8 on 2025-12-24 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='The subject or topic for content generation', max_length=500, validators=[django.core.validators.MinLengthValidator(3)])),
                ('style', models.CharField(choices=[('brief', 'Brief'), ('detailed', 'Detailed'), ('step_by_step', 'Step-by-Step')], default='detailed', help_text='Content generation style preference', max_length=20)),
                ('format', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('worksheet', 'Worksheet')], default='text', help_text='Desired output format', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current processing status', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional request parameters (e.g., difficulty level, prerequisites)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the request was last updated')),
            ],
            options={
                'verbose_name': 'Content Request',
                'verbose_name_plural': 'Content Requests',
                'db_table': 'content_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='cr_created_status_idx'), models.Index(fields=['status', 'updated_at'], name='cr_status_updated_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='The generated content body')),
                ('format', models.CharField(choices=[('summary', 'Summary'), ('worked_example', 'Worked Example'), ('formula_sheet', 'Formula Sheet'), ('study_plan', 'Study Plan'), ('concept_explanation', 'Concept Explanation')], default='summary', help_text='Type of generated content', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about content generation (model, tokens, parameters)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when content was generated')),
                ('request', models.ForeignKey(help_text='The content request this content fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='content_requests.contentrequest')),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Contents',
                'db_table': 'generated_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='gc_request_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('report_issue', 'Report Issue'), ('suggestion', 'Suggestion')], db_index=True, help_text='Type of feedback provided', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Detailed feedback comments or suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when feedback was submitted')),
                ('request', models.ForeignKey(help_text='The content request being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='content_requests.contentrequest')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='uf_request_created_idx'), models.Index(fields=['feedback_type', '-created_at'], name='uf_type_created_idx')],
            },
        ),
    ]
