# Generated by Django 5.2.8 on 2025-12-25 06:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the request', primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Subject matter for content generation', max_length=500, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content_type', models.CharField(choices=[('SUMMARY', 'SUMMARY'), ('WORKED_EXAMPLES', 'WORKED_EXAMPLES'), ('FORMULA_SHEET', 'FORMULA_SHEET')], help_text='Type of content to generate', max_length=50)),
                ('style', models.CharField(choices=[('BRIEF', 'BRIEF'), ('DETAILED', 'DETAILED'), ('STEP_BY_STEP', 'STEP_BY_STEP')], help_text='Generation style preference', max_length=50)),
                ('output_format', models.CharField(choices=[('TEXT', 'TEXT'), ('PDF', 'PDF'), ('WORKSHEET', 'WORKSHEET')], help_text='Desired output format', max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], help_text='Optional difficulty level', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional additional instructions or context', max_length=2000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', help_text='Current lifecycle status (system-managed)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when request was last updated')),
            ],
            options={
                'verbose_name': 'Content Request',
                'verbose_name_plural': 'Content Requests',
                'db_table': 'content_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cr_status_created_idx'), models.Index(fields=['-created_at'], name='cr_created_idx')],
            },
        ),
    ]
