# Generated by Django 5.2.8 on 2025-12-25 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for generated content', primary_key=True, serialize=False)),
                ('content_text', models.TextField(help_text='The raw generated content from AI')),
                ('output_format', models.CharField(choices=[('TEXT', 'TEXT'), ('PDF', 'PDF'), ('WORKSHEET', 'WORKSHEET')], help_text='Format of the generated content', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about content generation: AI model, tokens used, generation params, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when content was generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when content was last updated')),
                ('request', models.ForeignKey(help_text='The content request this content fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='content_requests.contentrequestmodel')),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Contents',
                'db_table': 'generated_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='gc_request_created_idx')],
            },
        ),
    ]
