# Generated by Django 5.2.8 on 2025-12-25 15:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_requests', '0002_generatedcontentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usefulness_rating', models.IntegerField(help_text='How useful was this content? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_rating', models.CharField(choices=[('TOO_EASY', 'Too Easy'), ('APPROPRIATE', 'Appropriate'), ('TOO_HARD', 'Too Hard')], help_text='Was the difficulty level appropriate?', max_length=20)),
                ('correctness_flag', models.BooleanField(help_text='Was the content factually correct?')),
                ('missing_topics', models.TextField(blank=True, help_text='Topics that should have been included (optional)', null=True)),
                ('freeform_comment', models.TextField(blank=True, help_text='Additional feedback or suggestions (optional)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When feedback was submitted')),
                ('generated_content', models.OneToOneField(help_text='The generated content being rated', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='content_requests.generatedcontentmodel')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['generated_content'], name='feedback_generat_d3b5bf_idx'), models.Index(fields=['submitted_at'], name='feedback_submitt_bdf073_idx'), models.Index(fields=['usefulness_rating'], name='feedback_usefuln_f49cc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('generated_content',), name='unique_feedback_per_content')],
            },
        ),
    ]
