# Generated by Django 5.2.8 on 2025-12-25 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_requests', '0003_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContextModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_goal', models.CharField(blank=True, choices=[('REVISION', 'Revision/Review'), ('CONCEPT_CLARITY', 'Concept Clarity'), ('EXAM_PREP', 'Exam Preparation'), ('PRACTICE', 'Practice/Application')], help_text='Primary learning goal for this content', max_length=20, null=True)),
                ('self_reported_weaknesses', models.JSONField(blank=True, default=list, help_text='Topics/concepts the user wants to focus on (manual input)')),
                ('preferred_depth', models.CharField(choices=[('SHALLOW', 'Quick Overview'), ('NORMAL', 'Standard Detail'), ('DEEP', 'In-Depth Explanation')], default='NORMAL', help_text='How detailed should explanations be?', max_length=10)),
                ('time_constraint', models.CharField(choices=[('QUICK', 'Quick (10-15 min)'), ('NORMAL', 'Normal (30-45 min)'), ('EXTENSIVE', 'Extensive (60+ min)')], default='NORMAL', help_text='Available time for studying this content', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional context or requirements (optional)', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When context was provided')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update to context')),
                ('content_request', models.OneToOneField(help_text='The content request this context applies to', on_delete=django.db.models.deletion.CASCADE, related_name='learning_context', to='content_requests.contentrequestmodel')),
            ],
            options={
                'db_table': 'learning_context',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_request'], name='learning_co_content_a9ed81_idx'), models.Index(fields=['target_goal'], name='learning_co_target__62febb_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_request',), name='unique_context_per_request')],
            },
        ),
    ]
