# Generated by Django 5.2.8 on 2025-12-26 06:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_requests', '0004_learningcontextmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the study plan', primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='User who owns this study plan (nullable until auth is integrated)', max_length=255, null=True)),
                ('name', models.CharField(help_text='Name of the study plan', max_length=200)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI-Driven')], default='manual', help_text='Plan creation mode: manual or AI-driven', max_length=20)),
                ('auto_detect_weakness', models.BooleanField(default=False, help_text='Enable automatic weak topic detection (requires Module 3)')),
                ('analytics_snapshot_id', models.UUIDField(blank=True, help_text='Reference to Module 3 analytics snapshot (future)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='study_plans_user_id_2ab5d1_idx'), models.Index(fields=['mode'], name='study_plans_mode_389869_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the study plan item', primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Topic or concept to study', max_length=500)),
                ('priority', models.IntegerField(default=3, help_text='Priority level (1=highest, 5=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('scheduled_date', models.DateField(blank=True, help_text='Target date to study this topic', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of this item', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manually Added'), ('analytics', 'Auto-detected by Analytics'), ('mixed', 'Analytics Suggested, User Modified')], default='manual', help_text='How this item was added: manual, analytics, or mixed', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Analytics confidence score for weakness detection (0.0-1.0, requires Module 3)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_request', models.ForeignKey(blank=True, help_text='Optional link to generated content request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_items', to='content_requests.contentrequestmodel')),
                ('study_plan', models.ForeignKey(help_text='Study plan this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content_requests.studyplan')),
            ],
            options={
                'db_table': 'study_plan_items',
                'ordering': ['priority', 'scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['study_plan', 'status'], name='study_plan__study_p_da3a41_idx'), models.Index(fields=['study_plan', 'priority'], name='study_plan__study_p_c11734_idx'), models.Index(fields=['source'], name='study_plan__source_e2b62c_idx')],
            },
        ),
    ]
