# Generated by Django 5.2.8 on 2026-02-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_change_is_active_default"),
        ("content_requests", "0005_studyplan_studyplanitem"),
        ("students", "0002_remove_studentprofile_student_class_class_section_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studyplan",
            name="study_plans_user_id_2ab5d1_idx",
        ),
        migrations.RemoveField(
            model_name="studyplan",
            name="user_id",
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_requests",
                to="authentication.customuser",
            ),
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="regenerated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original request this was regenerated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regenerations",
                to="content_requests.contentrequestmodel",
            ),
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                help_text="Role of the user who created this request",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Academic subject for this content",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="target_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Target class for this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.class",
            ),
        ),
        migrations.AddField(
            model_name="contentrequestmodel",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Target section for this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.section",
            ),
        ),
        migrations.AddField(
            model_name="feedbackmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_feedback",
                to="authentication.customuser",
            ),
        ),
        migrations.AddField(
            model_name="learningcontextmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who provided this context",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_contexts",
                to="authentication.customuser",
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this study plan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plans",
                to="authentication.customuser",
            ),
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "-created_at"], name="study_plans_user_id_2ab5d1_idx"
            ),
        ),
    ]
