# Generated by Django 5.2.8 on 2026-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_requests",
            "0006_remove_studyplan_study_plans_user_id_2ab5d1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrequestmodel",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Human-readable error message when request fails",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentrequestmodel",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("SUMMARY", "SUMMARY"),
                    ("WORKED_EXAMPLES", "WORKED_EXAMPLES"),
                    ("FORMULA_SHEET", "FORMULA_SHEET"),
                    ("LESSON_PLAN", "LESSON_PLAN"),
                    ("QUIZ_GENERATOR", "QUIZ_GENERATOR"),
                    ("WORKSHEET_BUILDER", "WORKSHEET_BUILDER"),
                    ("TOPIC_EXPLANATION", "TOPIC_EXPLANATION"),
                ],
                help_text="Type of content to generate",
                max_length=50,
            ),
        ),
    ]
