# Generated by Django 5.2.8 on 2026-03-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_requests", "0007_add_error_message_field"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrequestmodel",
            name="curriculum_topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Curriculum topic this content is generated for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_requests",
                to="curriculum.coursetopic",
            ),
        ),
    ]
