# Generated by Django 5.2.8 on 2025-12-26 12:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='ID of the learner')),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this insight was computed')),
                ('computation_rules_version', models.CharField(default='1.0.0', help_text='Version of rules used for computation', max_length=20)),
                ('events_analyzed_count', models.PositiveIntegerField(default=0, help_text='Number of events used in computation')),
                ('learning_pace', models.CharField(choices=[('very_slow', 'Very Slow'), ('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast'), ('very_fast', 'Very Fast')], default='moderate', help_text='Categorized learning pace', max_length=20)),
                ('pace_score', models.FloatField(default=0.5, help_text='Numeric pace score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('consistency_score', models.FloatField(default=0.5, help_text='Consistency score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('retry_frequency', models.FloatField(default=0.0, help_text='Retry frequency score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('average_difficulty', models.FloatField(default=0.5, help_text='Average difficulty across topics', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('average_mastery', models.FloatField(default=0.0, help_text='Average mastery across topics', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('overall_health_score', models.FloatField(default=0.5, help_text='Overall learning health score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weak_topics', models.JSONField(blank=True, default=list, help_text='List of weak topic names')),
                ('strong_topics', models.JSONField(blank=True, default=list, help_text='List of strong topic names')),
                ('topic_metrics', models.JSONField(blank=True, default=dict, help_text='Detailed metrics per topic')),
                ('extended_metrics', models.JSONField(blank=True, default=dict, help_text='Extended metrics for future use')),
            ],
            options={
                'verbose_name': 'Learner Insight',
                'verbose_name_plural': 'Learner Insights',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user_id', 'computed_at'], name='intelligenc_user_id_d29ee0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('content_started', 'Content Started'), ('content_completed', 'Content Completed'), ('content_abandoned', 'Content Abandoned'), ('content_regenerated', 'Content Regenerated'), ('topic_viewed', 'Topic Viewed'), ('topic_retried', 'Topic Retried'), ('topic_mastered', 'Topic Mastered'), ('plan_viewed', 'Plan Viewed'), ('plan_item_started', 'Plan Item Started'), ('plan_item_completed', 'Plan Item Completed'), ('plan_item_skipped', 'Plan Item Skipped'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('feedback_submitted', 'Feedback Submitted')], db_index=True, help_text='Type of learning event', max_length=50)),
                ('user_id', models.UUIDField(db_index=True, help_text='ID of the learner')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the event occurred')),
                ('topic', models.CharField(blank=True, db_index=True, help_text='Topic involved in this event', max_length=500, null=True)),
                ('content_request_id', models.UUIDField(blank=True, help_text='Related content request ID', null=True)),
                ('study_plan_id', models.UUIDField(blank=True, help_text='Related study plan ID', null=True)),
                ('study_plan_item_id', models.UUIDField(blank=True, help_text='Related study plan item ID', null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='Learning session ID for grouping', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the activity in seconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this event was recorded in the system')),
            ],
            options={
                'verbose_name': 'Learning Event',
                'verbose_name_plural': 'Learning Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='intelligenc_user_id_16f993_idx'), models.Index(fields=['user_id', 'event_type'], name='intelligenc_user_id_ca6895_idx'), models.Index(fields=['user_id', 'topic'], name='intelligenc_user_id_8b990c_idx'), models.Index(fields=['event_type', 'timestamp'], name='intelligenc_event_t_c1b99f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='ID of the learner')),
                ('recommendation_type', models.CharField(choices=[('recommend_review', 'Recommend Review'), ('recommend_retry', 'Recommend Retry'), ('recommend_reinforce', 'Recommend Reinforce'), ('recommend_slow_down', 'Recommend Slow Down'), ('recommend_speed_up', 'Recommend Speed Up'), ('recommend_break', 'Recommend Break'), ('recommend_reorder', 'Recommend Reorder'), ('recommend_prioritize', 'Recommend Prioritize'), ('recommend_defer', 'Recommend Defer'), ('recommend_simplify', 'Recommend Simplify'), ('recommend_elaborate', 'Recommend Elaborate'), ('recommend_alternative', 'Recommend Alternative'), ('recommend_focus', 'Recommend Focus'), ('recommend_practice', 'Recommend Practice')], db_index=True, help_text='Type of recommendation', max_length=50)),
                ('target_entity_type', models.CharField(help_text='Type of target (topic, content, plan, session)', max_length=20)),
                ('target_entity_id', models.UUIDField(blank=True, help_text='ID of target entity (if applicable)', null=True)),
                ('target_entity_name', models.CharField(help_text='Human-readable name of target', max_length=500)),
                ('justification', models.TextField(help_text='Human-readable explanation for this recommendation')),
                ('confidence_score', models.FloatField(help_text='Confidence score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='Priority level (1=highest, 5=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], db_index=True, default='active', help_text='Current status of recommendation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When recommendation was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When recommendation expires', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When recommendation was viewed', null=True)),
                ('actioned_at', models.DateTimeField(blank=True, help_text='When recommendation was acted upon', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional recommendation context')),
                ('source_insight', models.ForeignKey(blank=True, help_text='Insight that generated this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='intelligence.learnerinsight')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['priority', '-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='intelligenc_user_id_2bd797_idx'), models.Index(fields=['user_id', 'created_at'], name='intelligenc_user_id_593342_idx'), models.Index(fields=['recommendation_type', 'status'], name='intelligenc_recomme_633c95_idx')],
            },
        ),
    ]
