# Generated by Django 5.2.8 on 2026-02-07 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password_hash', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default='student', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authentication_user',
            },
        ),
    ]
