# Generated by Django 5.2.8 on 2025-12-30 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address (unique identifier)", max_length=254, unique=True)),
                ('full_name', models.CharField(help_text="User's full display name", max_length=255)),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], help_text="User's role determining their permissions", max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user was created')),
            ],
            options={
                'verbose_name': 'Tutoring User',
                'verbose_name_plural': 'Tutoring Users',
                'db_table': 'tutoring_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the session', primary_key=True, serialize=False)),
                ('room_id', models.CharField(help_text='LiveKit room identifier (format: tutoring_{uuid})', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for student'), ('ACTIVE', 'Session active'), ('GRACE', 'Grace period (teacher absent)'), ('ENDED', 'Session ended')], default='WAITING', help_text='Current session state', max_length=10)),
                ('livekit_token_teacher', models.TextField(blank=True, help_text='LiveKit access token for teacher', null=True)),
                ('livekit_token_student', models.TextField(blank=True, help_text='LiveKit access token for student', null=True)),
                ('grace_expires_at', models.DateTimeField(blank=True, help_text='When grace period expires (Phase 6)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session was created')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session was ended', null=True)),
                ('student', models.ForeignKey(blank=True, help_text='Student who joined this session (null if no student yet)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sessions', to='tutoring.tutoringuser')),
                ('teacher', models.ForeignKey(help_text='Teacher who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sessions', to='tutoring.tutoringuser')),
            ],
            options={
                'verbose_name': 'Tutoring Session',
                'verbose_name_plural': 'Tutoring Sessions',
                'db_table': 'tutoring_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_id'], name='tutoring_se_room_id_349819_idx'), models.Index(fields=['status'], name='tutoring_se_status_53b9aa_idx'), models.Index(fields=['teacher'], name='tutoring_se_teacher_fb6dd5_idx'), models.Index(fields=['student'], name='tutoring_se_student_bc4f30_idx')],
            },
        ),
    ]
