# Generated by Django 5.2.8 on 2026-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='active_screen_sharer',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], help_text='Role of the participant currently screen sharing (null if none)', max_length=10, null=True),
        ),
    ]
