# Generated by Django 5.2.8 on 2026-01-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_remove_screen_share_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='active_screen_sharer',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], help_text='Which participant is currently screen sharing (Phase 5)', max_length=10, null=True),
        ),
    ]
