# Generated by Django 5.2.8 on 2026-01-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_tutoringsession_active_screen_sharer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringsession',
            name='active_screen_sharer',
        ),
    ]
