# Generated by Django 5.2.8 on 2026-02-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_add_account_link_to_tutoring_user"),
        ("tutoring", "0005_remove_tutoringsession_active_screen_sharer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringuser",
            name="account",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the authentication account (nullable for legacy/test users)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutoring_profile",
                to="authentication.customuser",
            ),
        ),
    ]
