# Generated by Django 5.2.8 on 2026-02-11 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_change_is_active_default"),
        ("students", "0003_subject_teachersubjectassignment"),
        ("tutoring", "0007_migrate_to_custom_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "livekit_token",
                    models.TextField(
                        blank=True,
                        help_text="LiveKit access token for this participant",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tutoring_session_participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="tutoringsession",
            name="tutoring_se_student_bc4f30_idx",
        ),
        migrations.RemoveField(
            model_name="tutoringsession",
            name="livekit_token_student",
        ),
        migrations.RemoveField(
            model_name="tutoringsession",
            name="student",
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this session is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutoring_sessions",
                to="students.section",
            ),
        ),
        migrations.AlterField(
            model_name="tutoringsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting for students"),
                    ("ACTIVE", "Session active"),
                    ("GRACE", "Grace period (teacher absent)"),
                    ("ENDED", "Session ended"),
                ],
                default="WAITING",
                help_text="Current session state",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="tutoringsession",
            index=models.Index(
                fields=["section", "status"], name="tutoring_se_section_770e8d_idx"
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="tutoring.tutoringsession",
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_participations",
                to="authentication.customuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("session", "user"),
                name="unique_active_participant",
            ),
        ),
    ]
