# Generated by Django 5.2.8 on 2025-12-24 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the rubric', primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, help_text='Current version number of the rubric', validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current state of the rubric', max_length=20)),
                ('title', models.TextField(help_text='Title of the rubric')),
                ('subject', models.TextField(db_index=True, help_text='Subject area of the rubric')),
                ('question_text', models.TextField(help_text='The question text')),
                ('reference_answer', models.TextField(help_text='Model/reference answer for the question')),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks for the question', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('evaluation_rules', models.JSONField(default=list, help_text='List of evaluation rules in JSON format')),
                ('created_by', models.UUIDField(db_index=True, help_text='UUID of the user who created this rubric')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the rubric was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the rubric was last updated')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'db_table': 'rubrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'state'], name='rubrics_created_f57c49_idx'), models.Index(fields=['subject', 'state'], name='rubrics_subject_fc3a9b_idx'), models.Index(fields=['-created_at'], name='rubrics_created_81ceca_idx')],
            },
        ),
        migrations.CreateModel(
            name='RubricVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the version', primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Version number of this snapshot', validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(help_text='Complete snapshot of the rubric at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this version was created')),
                ('rubric', models.ForeignKey(help_text='Reference to the parent rubric', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rubrics.rubric')),
            ],
            options={
                'verbose_name': 'Rubric Version',
                'verbose_name_plural': 'Rubric Versions',
                'db_table': 'rubric_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['rubric', '-version_number'], name='rubric_vers_rubric__ecb982_idx'), models.Index(fields=['-created_at'], name='rubric_vers_created_89664e_idx')],
                'unique_together': {('rubric', 'version_number')},
            },
        ),
    ]
