# Generated by Django 5.2.8 on 2026-01-20 19:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_make_created_by_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the rubric set', primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Title of the assessment/rubric set')),
                ('subject', models.TextField(db_index=True, help_text='Subject area of the assessment')),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks for the entire assessment', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('version', models.IntegerField(default=1, help_text='Current version number of the rubric set', validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current state of the rubric set', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (duration, instructions, etc.)')),
                ('created_by', models.UUIDField(blank=True, db_index=True, help_text='UUID of the user who created this rubric set', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the rubric set was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the rubric set was last updated')),
            ],
            options={
                'verbose_name': 'Rubric Set',
                'verbose_name_plural': 'Rubric Sets',
                'db_table': 'rubric_sets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'state'], name='rubric_sets_created_50b202_idx'), models.Index(fields=['subject', 'state'], name='rubric_sets_subject_08b79f_idx'), models.Index(fields=['-created_at'], name='rubric_sets_created_16e71d_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the question rubric', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(help_text='Question number within the assessment (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('question_text', models.TextField(help_text='The question text')),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this question', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('evaluation_rules', models.JSONField(default=list, help_text='List of evaluation rules in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the question was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the question was last updated')),
                ('rubric_set', models.ForeignKey(help_text='Reference to the parent rubric set', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rubrics.rubricset')),
            ],
            options={
                'verbose_name': 'Question Rubric',
                'verbose_name_plural': 'Question Rubrics',
                'db_table': 'question_rubrics',
                'ordering': ['rubric_set', 'question_number'],
                'indexes': [models.Index(fields=['rubric_set', 'question_number'], name='question_ru_rubric__b21f35_idx')],
                'unique_together': {('rubric_set', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='RubricSetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the version', primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Version number of this snapshot', validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(help_text='Complete snapshot of the rubric set at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this version was created')),
                ('rubric_set', models.ForeignKey(help_text='Reference to the parent rubric set', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rubrics.rubricset')),
            ],
            options={
                'verbose_name': 'Rubric Set Version',
                'verbose_name_plural': 'Rubric Set Versions',
                'db_table': 'rubric_set_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['rubric_set', '-version_number'], name='rubric_set__rubric__06e8aa_idx'), models.Index(fields=['-created_at'], name='rubric_set__created_5accaf_idx')],
                'unique_together': {('rubric_set', 'version_number')},
            },
        ),
    ]
