# Generated by Django 5.2.8 on 2026-02-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_change_is_active_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_profile",
                        serialize=False,
                        to="authentication.customuser",
                    ),
                ),
                ("roll_number", models.CharField(max_length=30, unique=True)),
                (
                    "student_class",
                    models.CharField(
                        help_text="Class / Grade (e.g. '10', '12-Science')",
                        max_length=20,
                    ),
                ),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "father_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "father_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "mother_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fill only if different from parents",
                        max_length=100,
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "db_table": "students_profile",
            },
        ),
    ]
