# Generated by Django 5.2.8 on 2026-02-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_change_is_active_default"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_class",
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Grade or class name, e.g. '10', '12'", max_length=20
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional stream, e.g. 'Science', 'Commerce', 'Arts'",
                        max_length=50,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g. '2025-2026'", max_length=9),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["name", "stream"],
                "unique_together": {("name", "stream", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section identifier, e.g. 'A', 'B'", max_length=10
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40, help_text="Maximum number of students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="students.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "sections",
                "ordering": ["class_ref", "name"],
                "unique_together": {("class_ref", "name")},
            },
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="The section this student belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.section",
            ),
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="teacher_profile",
                        serialize=False,
                        to="authentication.customuser",
                    ),
                ),
                ("employee_id", models.CharField(max_length=30, unique=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Mathematics', 'Science'",
                        max_length=50,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'M.Sc. Mathematics', 'B.Ed'",
                        max_length=100,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Section where this teacher is the class teacher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_teacher",
                        to="students.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
                "db_table": "teachers_profile",
            },
        ),
    ]
