# Generated by Django 5.2.8 on 2026-02-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_change_is_active_default"),
        ("students", "0002_remove_studentprofile_student_class_class_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'ICT', 'Mathematics'", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 'ICT', 'MATH'", max_length=20, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="students.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="students.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="authentication.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_subject_assignments",
                "ordering": ["subject__name", "section__class_ref__name"],
                "unique_together": {("teacher", "subject", "section")},
            },
        ),
    ]
