"""
Database Models for Content Requests Module

This module defines the persistence layer for the AI-Assisted Content Request System.
It maps domain models to database tables using Django ORM.

The model is designed to be extensible for future phases (e.g., user associations,
analytics, versioning) without requiring schema migrations.
"""
import uuid
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator, MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _

from .domain.enums import ContentType, Style, OutputFormat, Difficulty, RequestStatus


class ContentRequestModel(models.Model):
    """
    ORM model for persisting ContentRequest domain entities.
    
    This is a thin persistence layer that stores domain model data.
    Business logic should NOT live here - it belongs in domain models and services.
    
    The model uses domain enums for consistency across the system.
    All status transitions must follow domain rules enforced in the service layer.
    
    Extension points:
    - user_id field can be added when authentication is implemented
    - metadata JSON field can store additional context for future features
    - generated_content_url can link to stored artifacts
    
    Indexing strategy:
    - Primary key (id) is UUID for distributed systems compatibility
    - status indexed for efficient filtering of pending/processing requests
    - created_at indexed for time-based queries
    """
    
    # Primary key - UUID for distributed system friendliness
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text=_("Unique identifier for the request")
    )
    
    # Required fields
    topic = models.CharField(
        max_length=500,
        validators=[MinLengthValidator(1)],
        help_text=_("Subject matter for content generation")
    )
    
    content_type = models.CharField(
        max_length=50,
        choices=ContentType.choices(),
        help_text=_("Type of content to generate")
    )
    
    style = models.CharField(
        max_length=50,
        choices=Style.choices(),
        help_text=_("Generation style preference")
    )
    
    output_format = models.CharField(
        max_length=50,
        choices=OutputFormat.choices(),
        help_text=_("Desired output format")
    )
    
    # Optional fields
    difficulty = models.CharField(
        max_length=50,
        choices=Difficulty.choices(),
        null=True,
        blank=True,
        help_text=_("Optional difficulty level")
    )
    
    notes = models.TextField(
        max_length=2000,
        null=True,
        blank=True,
        help_text=_("Optional additional instructions or context")
    )
    
    # System-managed fields
    status = models.CharField(
        max_length=50,
        choices=RequestStatus.choices(),
        default=RequestStatus.PENDING.value,
        db_index=True,
        help_text=_("Current lifecycle status (system-managed)")
    )
    
    # Timestamps
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when request was created")
    )
    
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text=_("Timestamp when request was last updated")
    )
    
    # Extension point for future phases
    # When authentication is implemented, add:
    # user = models.ForeignKey('user.User', on_delete=models.CASCADE, null=True, blank=True)
    
    # When content generation is implemented, add:
    # generated_content_url = models.URLField(null=True, blank=True)
    # error_message = models.TextField(null=True, blank=True)
    
    class Meta:
        db_table = 'content_requests'
        verbose_name = _('Content Request')
        verbose_name_plural = _('Content Requests')
        ordering = ['-created_at']
        indexes = [
            # Efficient querying for pending requests
            models.Index(fields=['status', 'created_at'], name='cr_status_created_idx'),
            # Time-based queries
            models.Index(fields=['-created_at'], name='cr_created_idx'),
        ]
    
    def __str__(self):
        return f"ContentRequest({self.id}): {self.topic[:50]} [{self.status}]"
    
    def __repr__(self):
        return (
            f"<ContentRequestModel id={self.id} status={self.status} "
            f"topic='{self.topic[:30]}...'>"
        )


class GeneratedContentModel(models.Model):
    """
    ORM model for storing AI-generated content.
    
    This model stores the actual content generated by AI providers in response
    to content requests. Each request can have one or more generated content items
    (for versioning or regeneration scenarios).
    
    The content is stored as text, and formatting is applied on retrieval based
    on the output_format field.
    
    Extension points:
    - version field can be added for content versioning
    - quality_score field can store AI confidence or user ratings
    - file_url can point to cloud storage for large files
    """
    
    # Primary key - UUID for distributed system friendliness
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text=_("Unique identifier for generated content")
    )
    
    # Foreign key to content request
    request = models.ForeignKey(
        ContentRequestModel,
        on_delete=models.CASCADE,
        related_name='generated_contents',
        help_text=_("The content request this content fulfills")
    )
    
    # Generated content
    content_text = models.TextField(
        help_text=_("The raw generated content from AI")
    )
    
    # Output format (stored for retrieval purposes)
    output_format = models.CharField(
        max_length=50,
        choices=OutputFormat.choices(),
        help_text=_("Format of the generated content")
    )
    
    # Metadata about generation
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text=_(
            "Metadata about content generation: "
            "AI model, tokens used, generation params, etc."
        )
    )
    
    # Timestamps
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when content was generated")
    )
    
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text=_("Timestamp when content was last updated")
    )
    
    class Meta:
        db_table = 'generated_content'
        verbose_name = _('Generated Content')
        verbose_name_plural = _('Generated Contents')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['request', 'created_at'], name='gc_request_created_idx'),
        ]
    
    def __str__(self):
        return f"GeneratedContent({self.id}): Request {self.request_id}"
    
    def __repr__(self):
        return (
            f"<GeneratedContentModel id={self.id} request_id={self.request_id} "
            f"format={self.output_format}>"
        )


# ============================================================================
# Phase 3: Feedback Models
# ============================================================================

class DifficultyRating(models.TextChoices):
    """Perceived difficulty level of generated content"""
    TOO_EASY = 'TOO_EASY', 'Too Easy'
    APPROPRIATE = 'APPROPRIATE', 'Appropriate'
    TOO_HARD = 'TOO_HARD', 'Too Hard'


class FeedbackModel(models.Model):
    """
    Structured feedback for generated content (Phase 3).
    
    Captures user feedback on AI-generated content quality.
    This data will be consumed by analytics modules in future phases.
    
    Design decisions:
    - One feedback per generated content (enforced at DB level)
    - All fields except comment are required for data quality
    - Cascade delete when content is deleted
    - No user association (pre-auth phase)
    
    Future extensions:
    - Add user_id when auth is implemented
    - Add feedback_version for schema evolution
    - Add moderation_status for quality control
    """
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    
    generated_content = models.OneToOneField(
        'GeneratedContentModel',
        on_delete=models.CASCADE,
        related_name='feedback',
        help_text='The generated content being rated'
    )
    
    usefulness_rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text='How useful was this content? (1-5)'
    )
    
    difficulty_rating = models.CharField(
        max_length=20,
        choices=DifficultyRating.choices,
        help_text='Was the difficulty level appropriate?'
    )
    
    correctness_flag = models.BooleanField(
        help_text='Was the content factually correct?'
    )
    
    missing_topics = models.TextField(
        blank=True,
        null=True,
        help_text='Topics that should have been included (optional)'
    )
    
    freeform_comment = models.TextField(
        blank=True,
        null=True,
        help_text='Additional feedback or suggestions (optional)'
    )
    
    submitted_at = models.DateTimeField(
        auto_now_add=True,
        help_text='When feedback was submitted'
    )
    
    class Meta:
        db_table = 'feedback'
        ordering = ['-submitted_at']
        indexes = [
            models.Index(fields=['generated_content']),
            models.Index(fields=['submitted_at']),
            models.Index(fields=['usefulness_rating']),
        ]
        # Enforce one feedback per content at database level
        constraints = [
            models.UniqueConstraint(
                fields=['generated_content'],
                name='unique_feedback_per_content'
            )
        ]
    
    def __str__(self):
        return f"Feedback for {self.generated_content_id} - {self.usefulness_rating}/5"
    
    @property
    def is_positive(self):
        """Helper to determine if feedback is generally positive"""
        return self.usefulness_rating >= 4 and self.correctness_flag


# Phase 4+ models will be added here
# Examples:
# - ContentVersionModel: tracks content revisions

